name: ci
on:
  push:
  workflow_dispatch:

jobs:
  volta:
    name: volta build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    #fails pretty often cause of network errors by download of yarn
    - uses: volta-cli/action@v4
    - uses: actions/cache@v4
      id: node_modules_cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-node_modules-
    - run: node --version
    - run: yarn --version
    - run: yarn install --frozen-lockfile

  corepack:
    name: corepack build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    #shows warning cause packageManager is not set in package.json but works
    - run: |
        corepack enable
        corepack install -g yarn@4.x
    - uses: actions/cache@v4
      id: node_modules_cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-node_modules-
    - run: node --version
    - run: yarn --version
    - run: yarn install --frozen-lockfile

  yarn:
    name: yarn build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    # modifies package.json and .yarnrc.yml which is not cool bot works...
    - run: |
        yarn set version 4.0.2
    - uses: actions/cache@v4
      id: node_modules_cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-node_modules-
    - run: node --version
    - run: yarn --version
    - run: yarn install --frozen-lockfile    
