name: ci
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: volta-cli/action@v4
    - uses: actions/cache@v3
      id: node_modules_cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-node_modules-
    - run: node --version
    - run: yarn --version
    - run: yarn install --frozen-lockfile
